# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,63,32]], np.int8)

In [3]:
myarr

array([[ 3,  4, 63, 32]], dtype=int8)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1]

4

In [7]:
myarr[0,1] = 63

In [8]:
myarr[0,1]

63

# Array creation: Conversion form other Python structures

In [10]:
listarray = np.array([[1,2,4],[5,7,8],[2,0,4]])

In [11]:
listarray

array([[1, 2, 4],
       [5, 7, 8],
       [2, 0, 4]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({23,43,86})

array({43, 86, 23}, dtype=object)

In [18]:
zeros = np.zeros((2,6))

In [22]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
rng = np.arange(15)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
lspace = np.linspace(1,50,10)

In [31]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [35]:
emp = np.empty((4,7))

In [36]:
emp

array([[1.03869630e-311, 9.43665384e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175,
        1.33600024e+165],
       [6.03369480e+174, 6.12595500e-062, 2.14703914e+184,
        1.45007427e-047, 3.59751658e+252, 8.76749093e+252,
        1.70537005e+256],
       [5.49109388e-143, 2.14027814e+161, 7.49874326e+247,
        2.25405648e+174, 6.19534370e-091, 3.93896325e-062,
        3.70080651e-033],
       [7.61101247e-042, 5.49810101e-143, 1.26087994e-076,
        2.29624044e-028, 8.59809677e-067, 4.50615877e-144,
        7.79952704e-143]])

In [37]:
emp_like = np.empty_like(lspace)

In [38]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [39]:
ide = np.identity(45)

In [40]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [41]:
ide.shape

(45, 45)

In [42]:
arr = np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr = arr.ravel()

In [49]:
arr.shape

(99,)

In [50]:
x = [[1,2,3],[4,5,6],[7,8,2]]

In [52]:
ar = np.array(x)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 2]])

In [54]:
ar.sum(axis=0)

array([12, 15, 11])

In [55]:
ar.sum(axis=1)

array([ 6, 15, 17])

In [56]:
ar.sum()

38

In [57]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 2]])

In [58]:
ar.flat

In [60]:
ar.ndim

2

In [61]:
ar.size

9

In [62]:
ar.nbytes

36

In [69]:
one = np.array([1,7,43,37])

In [70]:
one.argmax()

2

In [71]:
one.argmin()

0

In [72]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 2]])

In [74]:
ar.argmin()

0

In [75]:
ar.argmax()

7

In [76]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [77]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [78]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [79]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 2])

In [82]:
ar2 = np.array([[1,3,2],[5,4,3],[9,7,4]])

In [83]:
ar + ar2

array([[ 2,  5,  5],
       [ 9,  9,  9],
       [16, 15,  6]])

In [86]:
np.sqrt(ar+ar2)

array([[1.41421356, 2.23606798, 2.23606798],
       [3.        , 3.        , 3.        ],
       [4.        , 3.87298335, 2.44948974]])

In [93]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 2]])

In [98]:
np.where(ar>=5)

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 0, 1], dtype=int64))

In [99]:
np.count_nonzero(ar)

9

In [100]:
import sys

In [103]:
py_ar = [0,3,43,2]

In [104]:
np_ar = np.array(py_ar)

In [105]:
sys.getsizeof(1) * len(py_ar)

112

In [106]:
np_ar.itemsize * np_ar.size

16